execute pathogen#infect()
syntax on
filetype plugin indent on
set number

"syntax enable

"colorscheme desert
"set background=dark

"set encoding=utf8

"set ffs=unix,dos,mac

set nocompatible
    
set autoindent
set backup
set nu
set smartindent
"set showmatch
set textwidth=80
set title
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
   
syntax on
   
set t_Co=256
   
filetype on
filetype indent on
filetype plugin on
    
set modeline
set ls=2
let g:Powerline_symbols = "fancy"
colorscheme molokai
